---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-sentiment-config-map
data:
  LOGGING_FILE: "/var/logs/ml_sentiment.log"
  #DB_TEMPLATE: "postgres"
  DATABASE_HOST: "ml-sentiment-db-service"
  DATABASE_PORT: "5438"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-sentiment-pv-storage
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ./storage/models
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-sentiment-pv-logs
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ./volume/logs/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-sentiment-pvc-storage
spec:
  resources:
    requests:
      storage: 400Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-sentiment-pvc-logs
spec:
  resources:
    requests:
      storage: 400Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Secret
metadata:
  name: ml-sentiment-secret
data:
  POSTGRES_USER: "cG9zdGdyZXMK"
  POSTGRES_PASSWORD: "YVFXU3J0eTgwMgo="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-sentiment-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-sentiment-api
  template:
    metadata:
      labels:
        app: ml-sentiment-api
    spec:
      volumes:
        - name: pv-logs
          persistentVolumeClaim:
            claimName: ml-sentiment-pvc-logs
        - name: pv-storage
          persistentVolumeClaim:
            claimName: ml-sentiment-pvc-storage
      containers:
        - name: api
          image: ml-sentiment-analysis:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /var/logs/
              name: pv-logs
            - mountPath: /storage/models/
              name: pv-storage
          envFrom:
            - configMapRef:
                name: ml-sentiment-config-map
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ml-sentiment-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ml-sentiment-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-sentiment-db-deployment
spec:
  selector:
    matchLabels:
      app: ml-sentiment-db
  template:
    metadata:
      labels:
        app: ml-sentiment-db
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: ml-sentiment-pvc-storage
      containers:
        - name: db
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pv-storage
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ml-sentiment-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ml-sentiment-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ml-sentiment-api-service
  labels:
    app: ml-sentiment-api-service
spec:
  type: ClusterIP
  selector:
    app: ml-sentiment-api-deployment
  ports:
  - port: 9400
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-sentiment-db-service
  labels:
    app: my-sentiment-db-service
spec:
  type: ClusterIP
  selector:
    app: ml-sentiment-db-deployment
  ports:
  - port: 5438
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-sentiment-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: ml-sentiment-api-service
      port:
        number: 9400