---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-sentiment-config-map
data:
  LOGGING_FILE: "/var/logs/ml_sentiment.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-sentiment-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-sentiment-api
  template:
    metadata:
      labels:
        app: ml-sentiment-api
    spec:
      volumes:
        - name: pv-storage
      containers:
        - name: api
          image: ml-sentiment-analysis:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/var/logs/"
              name: pv-storage
          envFrom:
            - configMapRef:
                name: ml-sentiment-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: ml-sentiment-api-service
  labels:
    app: ml-sentiment-api-service
spec:
  type: ClusterIP
  selector:
    app: ml-sentiment-api
  ports:
  - port: 9400
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-sentiment-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: ml-sentiment-api-service
      port:
        number: 9400