---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-application-config-map
data:
  LOGGING_FILE: "/var/logs/ml_project.log"
  DB_TEMPLATE: "postgres"
  DATABASE_HOST: "ml-application-db-service"
  DATABASE_PORT: "5438"
---
apiVersion: v1
kind: Secret
metadata:
  name: ml-application-secret
data:
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "YVFXU3J0eTgwMg=="
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-application-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-application-api
  template:
    metadata:
      labels:
        app: ml-application-api
    spec:
      volumes:
        - name: pv-storage
      containers:
        - name: api
          image: ml-project-api:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "128m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/var/logs/"
              name: pv-storage
          envFrom:
            - configMapRef:
                name: ml-application-config-map
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ml-application-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ml-application-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-application-db-deployment
spec:
  selector:
    matchLabels:
      app: ml-application-db
  template:
    metadata:
      labels:
        app: ml-application-db
    spec:
      volumes:
        - name: pv-storage
      containers:
        - name: db
          image: postgres:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "128m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pv-storage
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ml-application-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ml-application-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ml-application-api-service
  labels:
    app: ml-application-api-service
spec:
  type: ClusterIP
  selector:
    app: ml-application-api
  ports:
  - port: 9400
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-application-db-service
  labels:
    app: my-sentiment-db-service
spec:
  type: ClusterIP
  selector:
    app: ml-application-db
  ports:
  - port: 5438
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-application-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: ml-application-api-service
      port:
        number: 9400