version: "3.9"
services:
  api:
    #image: "ml-sentiment-analysis:0.0.1"
    build: .
    ports:
      - "8200:8000/tcp"
    networks:
      - api-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - LOGGING_FILE=/var/logs/ml_sentiment.log
      - DB_TEMPLATE=postgres
      - DATABASE_HOST=db_host
      - DATABASE_PORT=5432
    env_file:
      - .db_credentials
    volumes:
      - ./api-logs/:/var/logs/
  database:
    image: "postgres:latest"
    container_name: "db_host"
    user: postgres # needed otherwise postgres container will use root, # FATAL: role "root" does not exist error
    ports:
      - "5438:5432"
    env_file:
      - .db_credentials
    networks:
      - api-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  api-network: