version: "3.9"
services:
  api:
    image: "rsalim1/ml-project-api:0.0.1"
    #build: .
    ports:
      - "8200:8000/tcp"
    networks:
      - api-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      - LOGGING_FILE=/var/logs/ml_project_ap.log
      - DB_TEMPLATE=postgres
      - DATABASE_HOST=db_host
      - DATABASE_PORT=5432
    env_file:
      - .db_credentials
    volumes:
      - ./volume/logs/:/var/logs/
      - ./storage:/storage/
  database:
    image: "postgres:latest"
    container_name: "db_host"
    #user: postgres # needed otherwise postgres container will use root, # FATAL: role "root" does not exist error
    ports:
      - "5438:5432"
    env_file:
      - .db_credentials
    networks:
      - api-network
    volumes:
      - ./volume/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  api-network: